# 使用 NVIDIA CUDA 的最新版基底映像
FROM nvidia/cuda:12.3.2-cudnn9-devel-ubuntu22.04

# 設定非交互式安裝，避免安裝過程中出現提示
ARG DEBIAN_FRONTEND=noninteractive
ENV PYTHON_VERSION=3.10
ARG CONDA_DIR=/opt/miniforge

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        cmake \
        build-essential \
        gcc \
        g++ \
        curl \
        git \
        software-properties-common \
        curl \
        locales \
        sudo \
        net-tools \
        wget \
        ffmpeg \
        libomp-dev \
        locale-gen && \
        echo "en_US.UTF-8 UTF-8" > /etc/locale.gen

RUN apt-get install --yes --no-install-recommends \
    gcc pkg-config libfreetype6-dev libpng-dev g++ \
    pandoc \
    libffi-dev 

RUN add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get update && \
    apt install -y python$PYTHON_VERSION python$PYTHON_VERSION-dev python3-pip python$PYTHON_VERSION-distutils gfortran libopenblas-dev liblapack-dev

    # python environment
RUN curl -sL https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -o miniforge.sh && \
    /bin/bash miniforge.sh -f -b -p $CONDA_DIR && \
    export PATH="$CONDA_DIR/bin:$PATH" && \
    conda config --set always_yes yes --set changeps1 no && \
    # lightgbm
    conda install -q -y numpy scipy scikit-learn pandas && \
    git clone --recursive --branch stable --depth 1 https://github.com/Microsoft/LightGBM && \
    cd ./LightGBM && \
    sh ./build-python.sh install && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# 更新 pip 並安裝 Jupyter Lab 和其他 Python 庫
RUN python3 -m pip install --upgrade pip requests setuptools pipenv && \
    pip install jupyterlab \
                yt-dlp \
                pandas \
                numpy \
                matplotlib \
                scikit-learn \
                tensorflow \
                keras \
                fastapi \
                uvicorn \
                pymongo \
                openai-whisper \
                psycopg2-binary \
                sqlalchemy \
                finlab \
                xgboost \
                catboost \
                torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113 \
                git+https://github.com/microsoft/qlib.git && \
    rm -r ~/.cache/pip


# 設定工作目錄
WORKDIR /workspace

# 運行 Jupyter Lab
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--LabApp.token=''"]
